server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://aa1lqi0ybvmkzdj.cdipsbpbyrhx.sa-east-1.rds.amazonaws.com:3306/ebdb
    username: admin
    password: testDBUdemy678
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false